language: node_js

git:
  depth: 10

install:
  - npm install -g @sourcegraph/lsif-tsc@0.6.0
  # Download src-cli as ./src-cli (not ./src) to avoid clash with src/ directory
  - curl -L https://github.com/sourcegraph/src-cli/releases/download/3.16.0/src_linux_amd64 -o ./src-cli
  - chmod +x ./src-cli
  - npm install
  - npm install -g grunt-cli

jobs:
  include:
    - name: Index and upload LSIF data to sourcegraph.com
      os: linux
      node_js: "13"
      script:
        - lsif-tsc **/*.js --AllowJs --checkJs
        - ./src-cli lsif upload -no-progress
